### PR TITLE
Css improved 

### LINKED ISSUE #11: Improve  the CSS of the page

### PR DESCRIPTION
**Pull request by soujo**
Resolves #11 

- Created an animated hamburger menu 
- Used icons instead of text for the buttons
- Used hovering effects at its best to understand the icons ( If users are unable to understand the icons )
- Fixed the horizontal scroll
- Made use of comments and appropriate naming variables

### CODE REVIEW

**Comment by soujo** [comment]
Resolved merge conflict

**Comment by ayush8010720467** [comment]
Please add the screenshot of the ui

**Comment by soujo** [comment]
Sure 
[Sample Video](https://drive.google.com/drive/folders/11l__m2HNksdCIVw35Sflh31_0UY3o-vc?usp=sharing)
Check this out @ayush8010720467

**Comment by ayush8010720467** [comment]
@soujo Please provide the acess for the same on ayushkatiyar096@gmail.com Or make it public.

**Comment by soujo** [comment]
Yes I have provided the access. Kindly check it @ayush8010720467

**Comment by ayush8010720467** [comment]
@soujo grey theme is not looking good. Can we try something like completly black and white? I have few more suggestion to make:
1: We are having 6 action right now. Can we have icons for them as well
2: Can we have a different icon for clear action? As we would be in the reqirement to add the eraser as upcoming feature
3: Can we have the icons stored in static/icons directory?

**Comment by soujo** [comment]
Okay so 

1. I will change the color of the navbar to black which is gray now, right?
Kindly answer the above one. 
2. I will look up to find the icons for the newly added buttons 
3. I will change the icon of clear 
4. Yep I will store the icons in the icons directory

**Comment by soujo** [comment]
Sure @ayush8010720467 
If the code till the previously asked points is fine and working then could you merge this pull request?
So that I could merge the css-improvement branch with my master and create a new branch for better accessibility, cause I am having some issues with git

**Comment by ayush8010720467** [comment]
@soujo I would have merged the PR, But 2 of the actions are missing. Cant merge it right now.

**Comment by soujo** [comment]
Okay. I will look into the issues.

**Comment by soujo** [comment]
Hey @ayush8010720467 
Look into these screenshots and say your opinion 
Should we go with the grey one?
Screenshot (185)
Or the black one?
Screenshot (186)

**Comment by bashutosh** [comment]
Black one looks good to me

**Comment by ayush8010720467** [comment]
@soujo Black one looks better to me as well.

**Comment by soujo** [comment]
Hey, @ayush8010720467 look into the code, I have solved the merge conflicts.

**Review by ayush8010720467 — APPROVED** [review]

**Pull request merged**
